/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import apoio.Formatacao;
import apoio.Validacao;
import dao.MovestoqueDAO;
import dao.ProdutoDAO;
import entidade.Movestoque;
import entidade.Produto;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Back
 */
public class IfrMovEstoque extends javax.swing.JInternalFrame {

    public IfrMovEstoque() {
        initComponents();
           
            tfdIdProd.setEditable(false);
            TfdDescricaoProd.setEditable(false);
            tfdCorProd.setEditable(false);
            tfdMarcaProd.setEditable(false);
            tfdTamanhoProd.setEditable(false);
            tfdQtdProd.setEditable(false);
            tfdSecaoProd.setEditable(false);
            tfdGrupoProd.setEditable(false);
            tfdPratProd.setEditable(false);
            Formatacao formata = new Formatacao();
            Formatacao.formatarData(tfdFdata);
            Formatacao.formatarHora(tfdThora);
            String t2;
    }
   
    public void limparcampos() {
        tfdIdProd.setText("");
        TfdDescricaoProd.setText("");
        tfdConsultarProduto.setText("");
        tfdCorProd.setText("");
        tfdFdata.setText("");
        tfdGrupoProd.setText("");
        tfdMarcaProd.setText("");
        tfdPratProd.setText("");
        tfdQtdMov.setText("");
        tfdQtdProd.setText("");
        tfdSecaoProd.setText("");
        tfdTamanhoProd.setText("");
        tfdThora.setText("");
        jComboEntradaSaida.setSelectedIndex(0);
        TMovEstoque.getSelectionModel().clearSelection();
    }
    
    
    public void carregaInfos () {
        String idString = String.valueOf(TMovEstoque.getValueAt(TMovEstoque.getSelectedRow(), 0));
      
     
        int idS = Integer.parseInt(idString);
        tfdIdProd.setEditable(false);
        // criar instancia ProdutoDAO
        ProdutoDAO prodDAO = new ProdutoDAO();

        // criar instancia Produto
        Produto produto = prodDAO.consultarIdAux(idS);

        if (produto != null) {
            
            // define os valores do obj nos campos da tela
            tfdIdProd.setText(""+produto.getId());
            TfdDescricaoProd.setText(produto.getDescricao());
            tfdCorProd.setText(produto.getCor());
            int aux;
            aux = produto.getCodsecao();
            System.out.println(aux);
            tfdMarcaProd.setText(produto.getMarca());
            tfdTamanhoProd.setText(produto.getTamanho());
            tfdQtdProd.setText(""+produto.getQtd());
            tfdSecaoProd.setText(produto.getSecao());
            tfdGrupoProd.setText(produto.getGrupo());
            tfdPratProd.setText(produto.getPrateleira());

            // mudar de aba
            //jTabbedPane1.setSelectedIndex(0);
            // definir o foco
            tfdConsultarProduto.requestFocus();
        }
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TMovEstoque = new javax.swing.JTable();
        tfdConsultarProduto = new javax.swing.JTextField();
        btnPesquisarProd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPesquisarProd1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TfdDescricaoProd = new javax.swing.JTextField();
        tfdIdProd = new javax.swing.JTextField();
        tfdMarcaProd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfdTamanhoProd = new javax.swing.JTextField();
        tfdCorProd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfdGrupoProd = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfdSecaoProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfdQtdProd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfdPratProd = new javax.swing.JTextField();
        btnCarregarInfo = new javax.swing.JButton();
        btnPesquisarProd3 = new javax.swing.JButton();
        jComboEntradaSaida = new javax.swing.JComboBox<>();
        tfdFdata = new javax.swing.JFormattedTextField();
        tfdQtdMov = new javax.swing.JFormattedTextField();
        tfdThora = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Movimentação de Estoque");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Consulta de Produtos");

        TMovEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Produto", "Grupo", "Qtd em Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TMovEstoque);

        btnPesquisarProd.setText("Salvar Lançamento");
        btnPesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdActionPerformed(evt);
            }
        });

        jLabel5.setText("Consulta");

        btnPesquisarProd1.setText("Pesquisar");
        btnPesquisarProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProd1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Informações do Produto Selecionado");

        jLabel7.setText("Descrição");

        jLabel8.setText("Marca");

        jLabel9.setText("Id");

        jLabel10.setText("Tamanho");

        jLabel11.setText("Cor");

        jLabel12.setText("Grupo");

        jLabel13.setText("Seção");

        jLabel14.setText("Prateleira");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Lançamento");

        jLabel2.setText("Data");

        jLabel3.setText("Quantidade Lançamento/Retirada");

        jLabel16.setText("Quantidade em Estoque");

        btnCarregarInfo.setText("Carregar Informações");
        btnCarregarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarInfoActionPerformed(evt);
            }
        });

        btnPesquisarProd3.setText("Fechar");
        btnPesquisarProd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProd3ActionPerformed(evt);
            }
        });

        jComboEntradaSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Entrada", "Saída" }));

        tfdFdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFdataActionPerformed(evt);
            }
        });

        tfdQtdMov.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tfdQtdMov.setToolTipText("");

        tfdThora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfdThora.setToolTipText("");

        jLabel17.setText("Hora");

        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(197, 197, 197))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(153, 153, 153)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarregarInfo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jComboEntradaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPesquisarProd3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfdDescricaoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdTamanhoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdCorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdGrupoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdPratProd, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfdQtdMov, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfdMarcaProd, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(tfdSecaoProd))
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tfdFdata, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdThora, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarProd))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(515, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboEntradaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnPesquisarProd1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarregarInfo)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfdIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfdTamanhoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TfdDescricaoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfdCorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfdMarcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfdGrupoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfdSecaoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfdPratProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfdQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdFdata, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdThora, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdQtdMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnPesquisarProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisarProd3)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(593, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(40, 40, 40)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdActionPerformed
         Formatacao formata = new Formatacao();
         Validacao valida = new Validacao();
         Movestoque Mov = new Movestoque();
         Produto prod = new Produto();
         MovestoqueDAO MovDAO = new MovestoqueDAO();
         /*carregaInfos();*/
         int aux = Integer.valueOf(tfdQtdMov.getText());
         int aux1 = Integer.valueOf(tfdIdProd.getText());
         int oper = jComboEntradaSaida.getSelectedIndex();
         String periodo = (tfdFdata.getText());
         String hora = (tfdThora.getText());
         String operacao = "";
         if (oper == 1) {
             operacao = "E";
         }
         if (oper == 2) {
             operacao = "S";
         }
         if (jComboEntradaSaida.getSelectedIndex() == 0) {
             JOptionPane.showMessageDialog(null, "Opção de Movimentação inválida");
         } else {
         if (valida.validarDataFormatada(tfdFdata.getText()) == false) {
             JOptionPane.showMessageDialog(null, "A data preenchida é inválida");
             System.out.println(tfdFdata.getText());
         } else { 
         if (valida.validaHora(tfdThora.getText()) == false) {
             JOptionPane.showMessageDialog(null, "A hora preenchida é inválida");
             System.out.println(tfdThora.getText());
         } else {
         if (jComboEntradaSaida.getSelectedIndex() == 2) {
            if (MovDAO.consultaEstoque(aux1, aux) == false) {
                JOptionPane.showMessageDialog(null, "Saldo insuficiente no estoque");
            } else {
            if (MovDAO.salvar(periodo,hora,aux,aux1,oper) == true && MovDAO.atualizaEstoque(aux, oper, aux1) == true)  {
             JOptionPane.showMessageDialog(null, "Estoque atualizado com sucesso!");
           }
           }
         } else {
          if (jComboEntradaSaida.getSelectedIndex() == 1) {
             if (MovDAO.salvar(periodo,hora,aux,aux1,oper) == true && MovDAO.atualizaEstoque(aux, oper, aux1) == true)  {
             JOptionPane.showMessageDialog(null, "Estoque atualizado com sucesso!");
             }
             
          }
                 }
                 }
         }
         }
    
           limparcampos();
           new MovestoqueDAO().popularTabela(TMovEstoque,tfdConsultarProduto.getText());
    }//GEN-LAST:event_btnPesquisarProdActionPerformed

    private void btnPesquisarProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProd1ActionPerformed
        new MovestoqueDAO().popularTabela(TMovEstoque,tfdConsultarProduto.getText());
    }//GEN-LAST:event_btnPesquisarProd1ActionPerformed

    private void btnCarregarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarInfoActionPerformed
       String idString = String.valueOf(TMovEstoque.getValueAt(TMovEstoque.getSelectedRow(), 0));
      
     
        int idS = Integer.parseInt(idString);
        tfdIdProd.setEditable(false);
        // criar instancia ProdutoDAO
        ProdutoDAO prodDAO = new ProdutoDAO();

        // criar instancia Produto
        Produto produto = prodDAO.consultarIdAux(idS);

        if (produto != null) {
            
            // define os valores do obj nos campos da tela
            tfdIdProd.setText(""+produto.getId());
            TfdDescricaoProd.setText(produto.getDescricao());
            tfdCorProd.setText(produto.getCor());
            int aux;
            aux = produto.getCodsecao();
            System.out.println(aux);
            tfdMarcaProd.setText(produto.getMarca());
            tfdTamanhoProd.setText(produto.getTamanho());
            tfdQtdProd.setText(""+produto.getQtd());
            tfdSecaoProd.setText(produto.getSecao());
            tfdGrupoProd.setText(produto.getGrupo());
            tfdPratProd.setText(produto.getPrateleira());

            // mudar de aba
            //jTabbedPane1.setSelectedIndex(0);
            // definir o foco
            tfdConsultarProduto.requestFocus();
        }
    }//GEN-LAST:event_btnCarregarInfoActionPerformed

    private void btnPesquisarProd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProd3ActionPerformed
        this.dispose();       
    }//GEN-LAST:event_btnPesquisarProd3ActionPerformed

    private void tfdFdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFdataActionPerformed

             
    }//GEN-LAST:event_tfdFdataActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TMovEstoque;
    private javax.swing.JTextField TfdDescricaoProd;
    private javax.swing.JButton btnCarregarInfo;
    private javax.swing.JButton btnPesquisarProd;
    private javax.swing.JButton btnPesquisarProd1;
    private javax.swing.JButton btnPesquisarProd3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboEntradaSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfdConsultarProduto;
    private javax.swing.JTextField tfdCorProd;
    private javax.swing.JFormattedTextField tfdFdata;
    private javax.swing.JTextField tfdGrupoProd;
    private javax.swing.JTextField tfdIdProd;
    private javax.swing.JTextField tfdMarcaProd;
    private javax.swing.JTextField tfdPratProd;
    private javax.swing.JFormattedTextField tfdQtdMov;
    private javax.swing.JTextField tfdQtdProd;
    private javax.swing.JTextField tfdSecaoProd;
    private javax.swing.JTextField tfdTamanhoProd;
    private javax.swing.JFormattedTextField tfdThora;
    // End of variables declaration//GEN-END:variables
}
